### ISSUE TITLE
Tracking issue for libz blitz evaluation

### ISSUE THREAD

**Issue by KodrAus** [dtolnay/semver#139]
[The original discussion and guidelines checklist](https://internals.rust-lang.org/t/out-of-band-crate-evaluation-for-2017-10-13-semver/5929)

Also see: [the `semver_parser` tracking issue](https://github.com/steveklabnik/semver-parser/issues/24)

We've extracted the following contribution opportunities out of the libz blitz evaluation of `semve`:

- [x] [Use `?` instead of `unwrap` in examples](https://github.com/steveklabnik/semver/issues/129)
- [x] [Document error cases on `Version::parse`](https://github.com/steveklabnik/semver/issues/130)
- [x] [Document error cases on `VersionReq::parse`](https://github.com/steveklabnik/semver/issues/131)
- [x] [Turn references to other `semver` items into links](https://github.com/steveklabnik/semver/issues/132)
- [x] [Add keywords and categories to Cargo.toml](https://github.com/steveklabnik/semver/issues/133)
- [x] [Add html_root_url attribute to crate root](https://github.com/steveklabnik/semver/issues/134)
- [x] [Make error types non-exhaustive](https://github.com/steveklabnik/semver/issues/135)
- [x] [Make fields on `Version` private](https://github.com/steveklabnik/semver/issues/136)
- [x] [Support range sets](https://github.com/steveklabnik/semver/issues/137)
- [x] [Rename VersionReq to Range](https://github.com/steveklabnik/semver/issues/138)

# We need your help!

- If you'd like to do one of these just leave a comment on the issue saying you're working on it.
- If it's been a little while since an issue was claimed and there isn't a PR yet then feel free to re-claim it.
- If you wanted to work on something but just didn't get around to it then don't feel bad! That's ok, and if you'd like to try something else we've got plenty more contribution opportunities. Just reach out on [gitter](https://gitter.im/rust-impl-period/WG-libz-blitz)

Some of these issues need more discussion so we can work out bigger design questions and put together mentoring instructions. It'd be great if you could leave your thoughts on those issues!

**Comment by dtolnay** [comment]
The above issues are all resolved and a 1.0.0 release candidate is published: https://docs.rs/semver/1.0.0-rc.1
