### ISSUE TITLE
Tracking issue: NPM compatible version ranges

### ISSUE THREAD

**Issue by mbrubeck** [dtolnay/semver#58]
- [x] #53 - Implement comparison rules for pre-release tags
- [ ] #55 - Allow whitespace-delimited comparator sets
- [ ] #56 - Implement hyphen ranges
- [ ] #57 - Support the `||` operator in version ranges

**Comment by steveklabnik** [comment]
:+1:

**Comment by ashleygwilliams** [comment]
o hey! this is awesome :space_invader: :ghost: :dolphin:

**Comment by kamalmarhubi** [comment]
Someone with edit perms: uncheck #57 since it was reopened. :-)

**Comment by hone** [comment]
@isaacs Is `~=` a valid semver operator? I noticed it works on <https://semver.npmjs.com>. I can't tell the difference between it and `~`. For context, we're looking to replace a piece of functionality on Heroku with a Rust binary that does semver version resolution for `node` and `yarn` versions. In the wild we're seeing `~=14.4`. /cc @danielleadams

**Comment by isaacs** [comment]
@hone So it is!

```
> semver.validRange('~=1.2.3')
'>=1.2.3 <1.3.0-0'
```

Kinda weird, imo.

**Comment by hone** [comment]
Thanks! So they are the same.

Doing a quick search, I don't see it the [semver range spec](https://github.com/semver/semver/pull/584/files) changes.

**Comment by dtolnay** [comment]
As of 1.0.0, this is no longer in scope for this crate, as described by https://github.com/dtolnay/semver/tree/1.0.0-rc.1#scope-of-this-crate. A separate https://crates.io/crates/node-semver crate may or may not happen depending on who is interested in maintaining it.
